bower.json

I run into an unexpected token when running ```bower install```
Patch is coming~

Fix bower install error

---

gulpfile.js
package.json

Hey Ej,
There are a few of gulpfile changes in this PR for build time improvement. I don't verify ./dist carefully, could you take a time to review it? thanks!

Introduce gulp-changed to speed up incremental build

---

src/backend/L10nManager.js

Allow kaku to be run outside of kaku directory (electron kaku).

Allow kaku to be run outside of kaku directory

---

bootup.js

Fix for #53

---

src/frontend/js/components/searchbar/container.js
src/frontend/less/components/sidebar.less
src/frontend/less/components/toolbar.less

1. hide AutoCompleteList when onBlur (UX+)
2. fixed dragging problem on toolbar

fixed #132, add padding for windows and others quickfixes

---

src/backend/locales/es.ini
src/backend/locales/metadata.json

*Writting Kaku on Spanish*.
There are some parts that I need to know if you want completly on Spanish or do you want to respect English. For example:
**Playlist**: I have not translated that word as "Lista de reproducción" because I have seen another programs translated on Spanish that keep that word on English.
**Tops Rankings**: I have not translated that because, although it is in English, in Spain is used the words "top" and "ranking" to refer the first positions, so I think it could be correct.
Then, the word **track** means "pista". I have translate that like "Pista de reproducción", but I have seen that in VLC they refers to that like "Pista de audio". I am going to research a bit more to specify correctly

Spanish Translation

---

src/frontend/js/components/searchbar/container.js

fixed #184, add small delay for onBlur to avoid cleaning up states too

---

src/frontend/js/main.js

fixed #194, for new users, they have no defaultLanguage, so we have to

---

src/frontend/js/components/toolbar/container.js

Fix missing semicolon

---

README.md
gulpfile.js

Fix for #202

---

src/main.js
src/modules/AutoUpdater.js
src/modules/KakuCore.js

This patch should work with another patch here https://github.com/EragonJ/node-youtube-dl/commit/3524cb9496c6f55c8c7096f17eb824cea01b0645

fixed #345, when bootup, we'll automatically update ytdl everytime !!

---

README.md

Fixed https://github.com/agnat/node_mdns/issues/160

Add a Linux dependency README.md

---

src/locales/metadata.json

corrects label for german translation

---

bootup.js
src/locales/ko.ini
src/locales/metadata.json

What got changed here :
- Add src/locales/ko.ini
- Update 'min-width' and 'min-height' to 'minWidth' and 'minHeight'
- Add label Korean in metadata.json
- Update label Korean in Korean

Create and update ko.ini

---

package.json
src/views/components/chatroom/comment/comment-form.js

#348 
This emoji picker is really rough, but it can works well. XD

Kaku emoji picker

---

src/views/modules/TabManager.js

rewrite src/views/modules/TabManager.js with ES6 syntax

---

src/modules/PlaylistManager.js
src/views/components/settings/index.js

Fix localBackup dialog

---

src/modules/importer/YoutubeImporter.js

rewrite src/modules/importer/YoutubeImporter.js with ES6 syntax

---

README.md

Found spelling error at top of README. Fixed spelling error.

Fixes spelling error in readme

---

src/views/components/topranking/index.js

rewrite src/views/componets/topranking

---

src/main.js

I was fixing spelling error (Detect a new... -> Detected a new...).
Then I thought that also popup heading and message could be improved. Feel free to dismiss this change if it is not ok per your standards.

Changed 'New Release' popup message

---

src/views/components/about/index.js

rewrite views/about with ES6 syntax

---

src/views/components/alltracks/index.js

rewrite views/alltracks with ES6 syntax

---

package.json

Update Kaku-core package version

---

src/views/components/playlist/index.js

fix playlist playAll button not work

---

README.md

I just changed the supported languages to reflect the native reading :)

Changed supported languages to reflect native spelling/reading

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

I think commits messages describes better than a 'short' description in this case :laughing:

Fix typo + format of issue and PR templates

---

src/views/modules/KonamiCodeManager.js
src/views/modules/Notifier.js

Revert "rewrite with ES6 syntax"

---

.github/ISSUE_TEMPLATE.md

Title is more than descriptive.

Update shorcut to access "Inspector" on Linux

---

config/api_config.development.json
package.json
src/main.js
src/modules/ErrorMonitor.js

added ErrorMonitor (based on Rollbar) to monitor any errors coming from clients.

fixed #501, added error monitor

---

package.json
src/views/components/connection-check/index.js
src/views/components/history/index.js
src/views/components/menus/index.js
src/views/components/news/index.js
src/views/components/news/news-tag.js
src/views/components/online-dj/index.js
src/views/components/player/control-buttons.js
src/views/components/player/index.js
src/views/components/player/track.js
src/views/components/searchbar/index.js

Part of important about [prop-types](https://facebook.github.io/react/docs/typechecking-with-proptypes.html).
In some component we use `PropType` from `React`, but in  **v15.5** need using `prop-types` instead.

Rewrite with ES6 syntax

---

src/main.js
src/views/components/searchbar/index.js

Fixed key id error and update src/main.js

---

README.md

Fixed bug:
What got changed here :
* fix erroneous github markdown syntax

Fix a typo reference
